# Generated by Django 4.2.1 on 2023-05-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilletest', '0003_remove_user_user_name_remove_user_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
