# Generated by Django 4.2.1 on 2023-05-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilletest', '0004_textinputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='textinputs',
            name='user_name',
            field=models.TextField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='textinputs',
            name='text',
            field=models.CharField(default='', max_length=140),
        ),
    ]
