# Generated by Django 4.2.1 on 2023-05-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilletest', '0005_textinputs_user_name_alter_textinputs_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinputs',
            name='user_name',
            field=models.CharField(default='', max_length=140),
        ),
    ]
