# Generated by Django 4.2.1 on 2023-05-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilletest', '0006_alter_textinputs_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinputs',
            name='text',
            field=models.TextField(default='', max_length=140),
        ),
    ]
