# Generated by Django 4.2.1 on 2023-05-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilletest', '0007_alter_textinputs_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('scraping_date', models.DateTimeField(auto_now_add=True)),
                ('scraping_time', models.CharField(default='', max_length=140)),
            ],
        ),
    ]
