# Generated by Django 4.2.1 on 2023-05-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilletest', '0008_scrapingcounter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapingcounter',
            old_name='scraping_date',
            new_name='scraping_date_at',
        ),
    ]
